version: '3'

services:
  postegres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "filipe50"
    ports:
      - "15432:5432"
    volumes:
      - ./data:/data/db

  api:
    container_name: api-container
    image: node
    working_dir: /usr/src/tibia-hunted-list
    restart: always
    command: bash -c "npm install --only=prod && npm install nodemon -D && npm run debug"
    volumes:
      - ./dist/:/usr/src/tibia-hunted-list/dist/
      - ./package.json:/usr/src/tibia-hunted-list/package.json
    ports:
      - "5050:5050"
      - "9222:9222"
    links:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "filipewk@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "filipe50"
    ports:
      - "16543:80"
    depends_on:
      - postegres
